# .github/workflows/ci-tests.yml
name: Run Selenium Tests CI

on:
  push:
    branches: [ main, master ] # Adjust branch name if needed
  pull_request:
    branches: [ main, master ] # Adjust branch name if needed

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin' # Or 'adopt', 'zulu', etc.

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository # Cache the local Maven repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Cache key based on OS and pom.xml
        restore-keys: |
          ${{ runner.os }}-maven- # Fallback restore key

    - name: Install Google Chrome # Needed for headless testing
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Tests with Maven (Headless Default)
      run: mvn clean test

    - name: Upload Extent Report Artifact
      uses: actions/upload-artifact@v4
      # Run this step even if the test step fails (to upload failure reports)
      if: always()
      with:
        name: extent-report
        path: test-output/extent-reports/*.html # Upload the generated HTML report

    - name: Upload Allure Results Artifact
      uses: actions/upload-artifact@v4
      # Run this step even if the test step fails
      if: always()
      with:
        name: allure-results
        path: target/allure-results # Upload the raw Allure results
        retention-days: 7 # Keep results for 7 days (optional) 