name: Selenium Grid Tests

on:
  workflow_dispatch:
    inputs:
      test-class:
        description: 'Test class to run'
        required: true
        default: 'LoginTest'
        type: string
      browser:
        description: 'Browser to use'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - both

jobs:
  run-grid-tests:
    runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/hub:4.16.1
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.16.1
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      firefox:
        image: selenium/node-firefox:4.16.1
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean compile -DskipTests

      - name: Run Tests on Chrome
        if: ${{ inputs.browser == 'chrome' || inputs.browser == 'both' }}
        run: |
          mvn test "-Dtest=${{ inputs.test-class }}" "-Dbrowser=chrome" "-Duse.grid=true" "-Dgrid.url=http://selenium-hub:4444"
        env:
          TEST_ENV: grid

      - name: Run Tests on Firefox
        if: ${{ inputs.browser == 'firefox' || inputs.browser == 'both' }}
        run: |
          mvn test "-Dtest=${{ inputs.test-class }}" "-Dbrowser=firefox" "-Duse.grid=true" "-Dgrid.url=http://selenium-hub:4444"
        env:
          TEST_ENV: grid

      - name: Upload Grid Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: grid-extent-report
          path: test-output/extent-reports/
          retention-days: 5

      - name: Upload Grid Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: grid-allure-results
          path: test-output/allure-results/
          retention-days: 5

      - name: Add Report Links to Job Summary
        if: always()
        run: |
          echo "### Grid Test Reports" >> $GITHUB_STEP_SUMMARY
          echo "📊 [Download Grid Extent Report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)" >> $GITHUB_STEP_SUMMARY
          echo "📜 [Download Grid Allure Results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Grid test reports have been uploaded as build artifacts." >> $GITHUB_STEP_SUMMARY 